sudo: false
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '4.2'
before_install:
  - npm i -g npm@^2.0.0
before_script:
  - npm prune
script:
  - npm run install-scope
  - npm run test-travis
after_success:
  - 'curl -Lo travis_after_all.py https://git.io/travis_after_all'
  - python travis_after_all.py
  - 'export $(cat .to_export_back) &> /dev/null'
  - npm run semantic-release
branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"
env:
  - TEST_SCOPE=1.2
  - TEST_SCOPE=1.3
  - TEST_SCOPE=1.4
